// Code generated by "stringer -type=OrderStatus --trimprefix OrderStatus"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OrderStatusNew-0]
	_ = x[OrderStatusRegistered-1]
	_ = x[OrderStatusProcessing-2]
	_ = x[OrderStatusProcessed-3]
	_ = x[OrderStatusInvalid-4]
}

const _OrderStatus_name = "NewRegisteredProcessingProcessedInvalid"

var _OrderStatus_index = [...]uint8{0, 3, 13, 23, 32, 39}

func (i OrderStatus) String() string {
	if i < 0 || i >= OrderStatus(len(_OrderStatus_index)-1) {
		return "OrderStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OrderStatus_name[_OrderStatus_index[i]:_OrderStatus_index[i+1]]
}
